//
// Created by prodigy on 25/12/2020.
//

#ifndef HOTELMANAGEMENTSYSTEM_MODIFYCUSTOMERINTERFACE_H
#define HOTELMANAGEMENTSYSTEM_MODIFYCUSTOMERINTERFACE_H


class ModifyCustomerInterface {

};


#endif //HOTELMANAGEMENTSYSTEM_MODIFYCUSTOMERINTERFACE_H
