//
// Created by prodigy on 17/12/2020.
//

#ifndef HOTELMANAGEMENTSYSTEM_CUSTOMERSTATE_H
#define HOTELMANAGEMENTSYSTEM_CUSTOMERSTATE_H
enum class CustomerState {
    COMING,NONE,REGISTERED
};
#endif //HOTELMANAGEMENTSYSTEM_CUSTOMERSTATE_H
