//
// Created by prodigy on 17/12/2020.
//

#ifndef HOTELMANAGEMENTSYSTEM_GENDER_H
#define HOTELMANAGEMENTSYSTEM_GENDER_H
enum class Gender {UNKNOW,MALE,FEMALE};
#endif //HOTELMANAGEMENTSYSTEM_GENDER_H
