//
// Created by prodigy on 23/12/2020.
//

#ifndef HOTELMANAGEMENTSYSTEM_ROOMSTATE_H
#define HOTELMANAGEMENTSYSTEM_ROOMSTATE_H
enum class RoomState {
    BUSY,EMPTY,CLEANING
};
#endif //HOTELMANAGEMENTSYSTEM_ROOMSTATE_H
